server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300 # 使用tcp进行连接
  rabbitmq:
      host: 127.0.0.1
      username: leyou
      password: leyou
      virtual-host: /leyou
      listener:
        simple:
          retry:  # 这部分可以代替事物注解使用
            enabled: true # 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
            max-attempts: 5 # 最大重试次数
            initial-interval: 5000ms  # 重试间隔时间（单位毫秒）
            default-requeue-rejected: false # 重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}