server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=UTF-8
    username: root
    password: 5456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: update  # 更新或创建数据表
    show-sql: true  # 控制台打印sql
  jackson:
      default-property-inclusion: non_null  # jackson返回的数据为null，不返回
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true # 返回eureka的是ip，而不是主机名
    ip-address: 127.0.0.1 # 设置返回的ip是啥
    instance-id: ${spring.application.name}:${server.port}

#logging:
#  level:
#    root: INFO
#    org:
#      springframework:
#        security: DEBUG
#        web: ERROR
#      hibernate: DEBUG
#      apache:
#        commons:
#          dbcp2: DEBUG
##  path: concretepage/logs
#  pattern:
#    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
#  file: mylogfile-manager.log
#
